name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install deps & Build
        run: bun i && mkdir -p dist && bun run build
 
      - name: Get current version from manifest
        id: version
        run: echo "version=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

      - name: Check if release already exists
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release view "${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "Release ${{ steps.version.outputs.version }} already exists. Skipping release and asset overwrite."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release
        if: steps.check.outputs.skip != 'true'
        uses: softprops/action-gh-release@v3
        with:
            tag_name: ${{ steps.version.outputs.version }}
            name: "EarthMC Dynmap+ (Owen3H Fork) v${{ steps.version.outputs.version }}"
            files: |
                dist/emc-dynmapplus.zip
                dist/emc-dynmapplus.user.js
            body: |
                [See changelog announcements](https://discord.com/channels/966271635894190090/966822836096364636)

                # 📜 Userscript
                1. Install a userscript manager (Violentmonkey recommended).
                1. Click [this link](https://github.com/EarthMC-Toolkit/earthmc-dynmap/releases/download/${{ steps.version.outputs.version }}/emc-dynmapplus.user.js) and hit **Install** or **Reinstall** to update.
                1. Make sure the script is enabled and refresh the map.

                # 📦 Chromium Extension
                ## First time prerequisites
                1. Head to your browser extension settings. 
                1. Click **Enable Developer Mode**.
                
                ## Installing or updating
                1. Download the `emc-dynmapplus.zip` file below and unzip it.
                1. Click **Load Unpacked** in your browser extension settings.
                1. Find the unzipped folder and select it, then refresh the map if you have it open.